# Generated by Django 3.2.25 on 2025-10-15 23:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='The polygon area for the analysis.', srid=4326, verbose_name='Geometry')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='The current status of the analysis request.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the request was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the request was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Analysis Request',
                'verbose_name_plural': 'Analysis Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
