# Generated by Django 3.2.25 on 2025-11-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='altitude_suitability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='precipitation_suitability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='slope_suitability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='soil_suitability',
            field=models.BooleanField(default=False),
        ),
    ]
