# Generated by Django 3.2.25 on 2025-11-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20251127_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='analysis.analysisrequest'),
        ),
    ]
