# Generated by Django 3.2.25 on 2025-11-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysisrequest_parent_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrequest',
            name='parent_request',
        ),
    ]
